const data = [
  {
    id: 1,
    avatar: "https://example.com/avatar1.jpg",
    name: "李明",
    age: 28,
    country: "印度",
    education: "高中",
    contact: "0922222222",
    address: "LUSUAC, PENARRUBIA, ABRA",
    sex: "female",
    skin: "fair",
    height: 152,
    weight: 50,
    birthday: "Oct 28, 1996",
    birthplace: "BANTAY, ILOCOS",
    nationality: "FILIPINO",
    religion: "JEHOVAH’S WITNESS",
    hobby: "SINGING, READING BOOKS",
    maritalStatus: "單身",
    familyStatus: {
      nameOfSpouse: "",
      childrenNo: 2,
      childrenAge: 6,
    },
    educational: "College",
    vocational: "",
    courseCompleted: "",
    specialSkill: "",
    language: {
      english: {
        speaking: "fair",
        writing: "fair",
      },
      chinese: {
        speaking: "fair",
        writing: "fair",
      },
    },
    cooking: "chinese",
    homeAppliance: "washing",
    babyCareSkill: "bathing",
    experience: "dawdawdawdawdwadwadwad",
  },
  {
    id: 2,
    avatar: "https://example.com/avatar2.jpg",
    name: "中本聪",
    age: 32,
    country: "菲律宾",
    education: "大学",
    contact: "09123456789",
    address: "Manila, Philippines",
    sex: "male",
    skin: "tan",
    height: 175,
    weight: 68,
    birthday: "Jan 3, 1991",
    birthplace: "Tokyo, Japan",
    nationality: "Japanese",
    religion: "Buddhist",
    hobby: "Playing guitar, Cooking",
    maritalStatus: "married",
    familyStatus: {
      nameOfSpouse: "Satomi Nakamura",
      childrenNo: 1,
      childrenAge: 4,
    },
    educational: "Bachelor's Degree",
    vocational: "",
    courseCompleted: "",
    specialSkill: "",
    language: {
      english: {
        speaking: "fluent",
        writing: "fluent",
      },
      japanese: {
        speaking: "native",
        writing: "native",
      },
    },
    cooking: "Japanese, Italian",
    homeAppliance: "cooking, cleaning",
    babyCareSkill: "",
    experience: "Worked in IT industry for 5 years.",
  },
  {
    id: 3,
    avatar: "https://example.com/avatar3.jpg",
    name: "玛丽亚·加西亚",
    age: 24,
    country: "越南",
    education: "大学",
    contact: "0987654321",
    address: "Ho Chi Minh City, Vietnam",
    sex: "female",
    skin: "fair",
    height: 165,
    weight: 55,
    birthday: "May 15, 1999",
    birthplace: "Hanoi, Vietnam",
    nationality: "Vietnamese",
    religion: "Catholic",
    hobby: "Painting, Traveling",
    maritalStatus: "single",
    familyStatus: {
      nameOfSpouse: "",
      childrenNo: 0,
      childrenAge: 0,
    },
    educational: "Bachelor's Degree",
    vocational: "",
    courseCompleted: "",
    specialSkill: "",
    language: {
      english: {
        speaking: "fluent",
        writing: "fluent",
      },
      vietnamese: {
        speaking: "native",
        writing: "native",
      },
    },
    cooking: "Vietnamese, French",
    homeAppliance: "gardening",
    babyCareSkill: "",
    experience: "Interned at an architecture firm for 2 years.",
  },
  {
    id: 4,
    avatar: "https://example.com/avatar4.jpg",
    name: "拉维·帕特尔",
    age: 30,
    country: "印度",
    education: "大学",
    contact: "0976543210",
    address: "New Delhi, India",
    sex: "male",
    skin: "olive",
    height: 180,
    weight: 75,
    birthday: "Sep 12, 1993",
    birthplace: "Mumbai, India",
    nationality: "Indian",
    religion: "Hinduism",
    hobby: "Yoga, Reading",
    maritalStatus: "single",
    familyStatus: {
      nameOfSpouse: "",
      childrenNo: 0,
      childrenAge: 0,
    },
    educational: "Bachelor's Degree",
    vocational: "",
    courseCompleted: "",
    specialSkill: "",
    language: {
      english: {
        speaking: "fluent",
        writing: "fluent",
      },
      hindi: {
        speaking: "native",
        writing: "native",
      },
    },
    cooking: "Indian, Mediterranean",
    homeAppliance: "carpentry",
    babyCareSkill: "",
    experience: "Worked as a software developer for 6 years.",
  },
  {
    id: 5,
    avatar: "https://example.com/avatar5.jpg",
    name: "艾米丽·约翰逊",
    age: 26,
    country: "菲律宾",
    education: "國中",
    contact: "0943210987",
    address: "Cebu City, Philippines",
    sex: "female",
    skin: "fair",
    height: 160,
    weight: 52,
    birthday: "Dec 5, 1997",
    birthplace: "Manila, Philippines",
    nationality: "FILIPINO",
    religion: "Christianity",
    hobby: "Dancing, Photography",
    maritalStatus: "single",
    familyStatus: {
      nameOfSpouse: "",
      childrenNo: 0,
      childrenAge: 0,
    },
    educational: "High School",
    vocational: "",
    courseCompleted: "",
    specialSkill: "",
    language: {
      english: {
        speaking: "fluent",
        writing: "fluent",
      },
      tagalog: {
        speaking: "native",
        writing: "native",
      },
    },
    cooking: "Filipino, Spanish",
    homeAppliance: "sewing",
    babyCareSkill: "",
    experience: "Worked in customer service for 3 years.",
  },
];

export default data;
